//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllItemInGroup
    {
        public int ItemGroupNo { get; set; }
        public Nullable<int> Countofitem { get; set; }
        public Nullable<int> Count { get; set; }
        public int StoreID { get; set; }
    }
}
