//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstCity
    {
        public long ID_NO { get; set; }
        public short Cmp_No { get; set; }
        public short Actvty_No { get; set; }
        public short City_No { get; set; }
        public Nullable<short> Prnt_City { get; set; }
        public Nullable<short> Level_no { get; set; }
        public Nullable<short> Level_Status { get; set; }
        public string City_NmAR { get; set; }
        public string City_NmEN { get; set; }
        public Nullable<int> Brn_No { get; set; }
        public Nullable<short> Cntry_No { get; set; }
    }
}
