//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAstRefTyp
    {
        public int ID_NO { get; set; }
<<<<<<< HEAD
        public short Cmp_No { get; set; }
        public short Actvty_No { get; set; }
        public short RefTyp_No { get; set; }
        public Nullable<short> Prnt_RefTyp { get; set; }
        public Nullable<short> Level_no { get; set; }
        public Nullable<short> Level_Status { get; set; }
        public string RefTyp_NmAr { get; set; }
        public string RefTyp_NmEn { get; set; }
=======
        public short Main_Reftyp { get; set; }
        public short RefTyp_No { get; set; }
        public string RefTyp_Nm { get; set; }
        public string RefTyp_NmAr { get; set; }
        public Nullable<int> cmp_no { get; set; }
>>>>>>> 292cc9635701abdad279c3fdf75cc90850de5602
    }
}
