//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsFixdAsets
    {
        public long ID_NO { get; set; }
        public short Cmp_No { get; set; }
        public double Brn_No { get; set; }
        public double Aset_No { get; set; }
        public double Parnt_Acc { get; set; }
        public Nullable<double> Level_No { get; set; }
        public Nullable<double> Level_Status { get; set; }
        public Nullable<double> Loc_No { get; set; }
        public Nullable<double> Unit_Code { get; set; }
        public string Aset_Nm { get; set; }
        public string Aset_NmEn { get; set; }
        public Nullable<double> Aset_Actvty { get; set; }
        public Nullable<double> Aset_Typ { get; set; }
        public Nullable<decimal> Book_Value { get; set; }
        public string Depr_StDt { get; set; }
        public Nullable<double> DeprSt_No { get; set; }
        public Nullable<decimal> Pursh_Value { get; set; }
        public string Pursh_Dt { get; set; }
        public string Pursh_Issue { get; set; }
        public Nullable<double> Acc_DB { get; set; }
        public Nullable<double> Acc_CR { get; set; }
        public string Sup_Nm { get; set; }
        public string Garnt_Cond { get; set; }
        public string Garnt_StDt { get; set; }
        public string Garnt_EndDt { get; set; }
        public string Insur_Issue { get; set; }
        public Nullable<decimal> Insur_Value { get; set; }
        public string Insur_StDt { get; set; }
        public string Insur_EndDt { get; set; }
        public string Aset_Recp { get; set; }
        public string Aset_CmpNo { get; set; }
        public string Tot_Depr { get; set; }
        public string Mnth_Depr { get; set; }
        public string AsetCmp_No { get; set; }
        public Nullable<double> DeprSt_No1 { get; set; }
        public Nullable<decimal> Dep_Mnth1 { get; set; }
        public Nullable<decimal> Dep_Mnth2 { get; set; }
        public Nullable<decimal> Dep_Mnth3 { get; set; }
        public Nullable<decimal> Dep_Mnth4 { get; set; }
        public Nullable<decimal> Dep_Mnth5 { get; set; }
        public Nullable<decimal> Dep_Val1 { get; set; }
        public Nullable<decimal> Dep_Val2 { get; set; }
        public Nullable<decimal> Dep_Val3 { get; set; }
        public Nullable<decimal> Dep_Val4 { get; set; }
        public Nullable<decimal> Dep_Val5 { get; set; }
        public string Dep_yer1 { get; set; }
        public string Dep_Yer2 { get; set; }
        public string Dep_Yer3 { get; set; }
        public string Dep_Yer4 { get; set; }
        public string Dep_Yer5 { get; set; }
        public string Ownr_No { get; set; }
        public string Depm_No { get; set; }
        public string Recp_Dt { get; set; }
        public string Ex_Recp { get; set; }
        public string recp_typ { get; set; }
        public Nullable<decimal> Dep_YearPrcnt { get; set; }
        public Nullable<decimal> Dep_MonthPrcnt { get; set; }
        public Nullable<decimal> Dep_NofYear { get; set; }
        public Nullable<decimal> Dep_NofMonth { get; set; }
        public string Notes { get; set; }
        public string FBal_DB { get; set; }
        public string FBal_CR { get; set; }
        public string MFld_CR { get; set; }
        public string MFld_DB { get; set; }
        public Nullable<double> Ac_AstsDBNo { get; set; }
        public Nullable<double> Ac_AstsCRNo { get; set; }
        public string Itm_no { get; set; }
        public string Doc_No { get; set; }
        public string Ln_No { get; set; }
        public string Doc_Ty { get; set; }
        public string Doc_Serial { get; set; }
    }
}
