//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsItmMfs
    {
        public short Cmp_No { get; set; }
        public short Actvty_No { get; set; }
        public long Itm_No { get; set; }
        public long Parent_Itm { get; set; }
        public Nullable<short> Level_No { get; set; }
        public Nullable<short> Level_Status { get; set; }
        public Nullable<int> Measure_Grp { get; set; }
        public Nullable<short> Itm_Active { get; set; }
        public Nullable<short> Sale_Active { get; set; }
        public Nullable<short> Invt_Active { get; set; }
        public Nullable<short> Itm_Req { get; set; }
        public Nullable<short> Itm_Relation { get; set; }
        public Nullable<long> Itm_No_Main { get; set; }
        public string Ref_No { get; set; }
        public Nullable<short> Dpm_No { get; set; }
        public string Itm_NmAr { get; set; }
        public string Itm_NmEn { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<short> Unit_No { get; set; }
        public Nullable<short> UnitPur_No { get; set; }
        public Nullable<short> UnitSaL_No { get; set; }
        public Nullable<int> Req_Limit { get; set; }
        public Nullable<decimal> Itm_Pur { get; set; }
        public Nullable<decimal> Itm_COst { get; set; }
        public Nullable<decimal> Itm_Sal1 { get; set; }
        public Nullable<decimal> Itm_Sal2 { get; set; }
        public Nullable<decimal> Itm_Sal3 { get; set; }
        public string Item_BarCode { get; set; }
        public string Fctry_Barcode { get; set; }
        public string Fctry_Barcode2 { get; set; }
        public string Fctry_Barcode3 { get; set; }
        public Nullable<short> Grup1 { get; set; }
        public Nullable<short> Grup2 { get; set; }
        public Nullable<short> Grup3 { get; set; }
        public Nullable<short> Grup31 { get; set; }
        public Nullable<short> MaxQty_SaL { get; set; }
        public Nullable<decimal> Prct_SalBouns { get; set; }
        public Nullable<short> Chk_SalBouns { get; set; }
        public Nullable<short> Chk_Discount { get; set; }
        public Nullable<decimal> Prct_Discount { get; set; }
        public Nullable<short> Chk_ExpDate { get; set; }
        public Nullable<short> Chk_Batch { get; set; }
        public Nullable<short> Chk_Qty2 { get; set; }
        public Nullable<short> Chk_Qty3 { get; set; }
        public Nullable<short> Pckng_Unit { get; set; }
        public Nullable<short> Pckng_Ratio { get; set; }
        public Nullable<decimal> Taxp_Extra { get; set; }
        public Nullable<short> Tax_Allow { get; set; }
        public Nullable<short> Chk_SalComsion { get; set; }
        public Nullable<short> Label_No { get; set; }
        public string Shelf_No { get; set; }
        public string Updt_Date { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
