//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsItmcatgry
    {
        public short Cmp_No { get; set; }
        public short Actvty_No { get; set; }
        public short Catg_No { get; set; }
        public long Parnet_Catg { get; set; }
        public Nullable<short> Level_No { get; set; }
        public Nullable<short> Level_Status { get; set; }
        public Nullable<short> Itm_Active { get; set; }
        public string Itm_NmAr { get; set; }
        public string Itm_NmEn { get; set; }
        public Nullable<long> Sup_No { get; set; }
        public Nullable<short> Dpm_No { get; set; }
        public Nullable<short> Sales_Kind { get; set; }
        public string Opn_Date { get; set; }
        public string Opn_Time { get; set; }
        public string User_ID { get; set; }
        public Nullable<System.DateTime> Updt_Date { get; set; }
        public long Parent_Itm { get; set; }
    }
}
