//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsItmOthr
    {
        public short Cmp_No { get; set; }
        public short Actvty_No { get; set; }
        public long Itm_No { get; set; }
        public long Parent_Itm { get; set; }
        public Nullable<decimal> Itm_TWeight { get; set; }
        public Nullable<decimal> Itm_NWeight { get; set; }
        public string Itm_Length { get; set; }
        public string Itm_Width { get; set; }
        public string Itm_Height { get; set; }
        public string Itm_Durability { get; set; }
        public string Shelf_No { get; set; }
        public string Itm_Othr1 { get; set; }
        public string Itm_Othr2 { get; set; }
        public string Updt_Date { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
