//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtsSuplir
    {
        public int ID_NO { get; set; }
        public short Cmp_No { get; set; }
        public int Brn_No { get; set; }
        public long Sup_No { get; set; }
        public long Parnt_Sup { get; set; }
        public Nullable<short> Level_no { get; set; }
        public Nullable<short> Level_Status { get; set; }
        public Nullable<short> Sup_Active { get; set; }
        public string Sup_NmAr { get; set; }
        public string Sup_NmEn { get; set; }
        public string Sup_Refno { get; set; }
        public Nullable<short> SupCtg_No { get; set; }
        public Nullable<short> Cntry_No { get; set; }
        public string Sup_Adr { get; set; }
        public Nullable<short> Curncy_No { get; set; }
        public string Sup_Email { get; set; }
        public string Sup_Tel { get; set; }
        public string Sup_Mobile { get; set; }
        public string Sup_Fax { get; set; }
        public string Tel1 { get; set; }
        public string Mobile1 { get; set; }
        public Nullable<long> Acc_No { get; set; }
        public Nullable<decimal> Credit_Value { get; set; }
        public Nullable<int> Credit_Days { get; set; }
        public Nullable<short> TradeOffer { get; set; }
        public string Tax_No { get; set; }
        public Nullable<decimal> Fbal_Db { get; set; }
        public Nullable<decimal> Fbal_CR { get; set; }
        public Nullable<decimal> CR11 { get; set; }
        public Nullable<decimal> CR12 { get; set; }
        public Nullable<decimal> CR13 { get; set; }
        public Nullable<decimal> CR14 { get; set; }
        public Nullable<decimal> CR15 { get; set; }
        public Nullable<decimal> CR16 { get; set; }
        public Nullable<decimal> CR17 { get; set; }
        public Nullable<decimal> CR18 { get; set; }
        public Nullable<decimal> CR19 { get; set; }
        public Nullable<decimal> CR20 { get; set; }
        public Nullable<decimal> CR21 { get; set; }
        public Nullable<decimal> CR22 { get; set; }
        public Nullable<decimal> DB11 { get; set; }
        public Nullable<decimal> DB12 { get; set; }
        public Nullable<decimal> DB13 { get; set; }
        public Nullable<decimal> DB14 { get; set; }
        public Nullable<decimal> DB15 { get; set; }
        public Nullable<decimal> DB16 { get; set; }
        public Nullable<decimal> DB17 { get; set; }
        public Nullable<decimal> DB18 { get; set; }
        public Nullable<decimal> DB19 { get; set; }
        public Nullable<decimal> DB20 { get; set; }
        public Nullable<decimal> DB21 { get; set; }
        public Nullable<decimal> DB22 { get; set; }
        public Nullable<decimal> CBal { get; set; }
        public Nullable<long> LinvPur_No { get; set; }
        public string LinvPur_Dt { get; set; }
        public Nullable<decimal> LinvPur_Net { get; set; }
        public Nullable<long> LPymt_No { get; set; }
        public string LPymt_Dt { get; set; }
        public Nullable<decimal> LPymt_Db { get; set; }
        public Nullable<System.DateTime> Updt_Date { get; set; }
        public string User_ID { get; set; }
        public Nullable<decimal> Fbal_Rcpt { get; set; }
    }
}
