//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCert
    {
        public int PymLin_No { get; set; }
        public int PymItm_No { get; set; }
        public string PymItm_Dsc { get; set; }
        public string PymItm_Acc { get; set; }
        public string Expr1 { get; set; }
        public Nullable<decimal> Curnt_Pym { get; set; }
        public decimal PrevPayment { get; set; }
        public Nullable<decimal> NetPayment { get; set; }
        public int Prj_No { get; set; }
        public int PymCrt_No { get; set; }
    }
}
