//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stloddtlnutrbusn
    {
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public Nullable<long> Cstm_No { get; set; }
        public Nullable<decimal> Titm_Sal { get; set; }
        public Nullable<decimal> Disc1_Val { get; set; }
        public Nullable<decimal> Disc2_Val { get; set; }
        public Nullable<decimal> Othr_Disc { get; set; }
        public short Nutr_No { get; set; }
        public string Nutr_Nm { get; set; }
        public string Nutr_NmAr { get; set; }
    }
}
