//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class StsQry3
    {
        public int Doc_Ty { get; set; }
        public int Doc_No { get; set; }
        public int Ln_No { get; set; }
        public Nullable<int> item_No { get; set; }
        public Nullable<decimal> Bal_Qty { get; set; }
        public int Brn_No { get; set; }
        public Nullable<decimal> In_Qty { get; set; }
        public Nullable<decimal> Out_Qty { get; set; }
        public string Ds { get; set; }
        public string Doc_Dt { get; set; }
        public string Doc_Dt1 { get; set; }
    }
}
