//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniterror20
    {
        public long Itm_No { get; set; }
        public short StoreID { get; set; }
        public short Doc_Ty { get; set; }
        public long Doc_No { get; set; }
        public short Ln_No { get; set; }
        public string Ref_No { get; set; }
    }
}
