//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW3
    {
        public string Ref_No { get; set; }
        public string Itm_Nmar { get; set; }
        public int Cstm_Agrmnt { get; set; }
        public short Brn_No { get; set; }
        public long Cstm_No { get; set; }
        public string Cstm_Nmarb { get; set; }
        public Nullable<decimal> Unit_Sal1 { get; set; }
    }
}
