//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW1
    {
        public string Itm_Nmar { get; set; }
        public int Doc_No { get; set; }
        public short Ln_No { get; set; }
        public Nullable<int> Itm_No { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Bonus_Qty { get; set; }
        public Nullable<decimal> Itm_Pur { get; set; }
        public Nullable<decimal> TitmDisc_Val { get; set; }
        public Nullable<decimal> Titm_Val { get; set; }
        public string Exp_Date { get; set; }
        public string Unit_NmAr { get; set; }
        public Nullable<System.DateTime> Doc_Dt { get; set; }
        public int Sup_No { get; set; }
        public string Sup_NmAr { get; set; }
    }
}
