//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class viwItmUnit
    {
        public int Itm_No { get; set; }
        public string Unit_Nm { get; set; }
        public Nullable<short> Flg { get; set; }
        public string Unit_NmAr { get; set; }
        public Nullable<decimal> Itm_Sal1 { get; set; }
        public Nullable<decimal> Itm_Sal2 { get; set; }
        public Nullable<short> Unit_No { get; set; }
        public string Batch_No { get; set; }
        public Nullable<decimal> Itm_COst { get; set; }
        public string Shelf_life { get; set; }
        public string Exp_Date { get; set; }
        public Nullable<decimal> TitmDisc_Val { get; set; }
        public Nullable<decimal> TitmDisc_Prct { get; set; }
    }
}
