//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Collections.Generic;
    
    public partial class viwStkitm
    {
        public int StoreID { get; set; }
        public Nullable<int> Itm_No { get; set; }
        public string Itm_Nm { get; set; }
        public Nullable<short> Flg { get; set; }
        public string UnitNm { get; set; }
        public int Req_Lmit { get; set; }
        public int Max_Lmit { get; set; }
        public int Min_Lmit { get; set; }
        public decimal Opbl_Qty { get; set; }
        public decimal OpGroup_Qty { get; set; }
        public decimal Pur_Qty { get; set; }
        public decimal Trfrcp_Qty { get; set; }
        public decimal Rtsl_Qty { get; set; }
        public decimal Lost_Qty { get; set; }
        public decimal Rtpur_Qty { get; set; }
        public decimal Sal_Qty { get; set; }
        public decimal Trfdlv_Qty { get; set; }
        public decimal Adj_Qty { get; set; }
        public decimal Opbl_Cost { get; set; }
        public decimal Pur_Cost { get; set; }
        public decimal Rtpur_Cost { get; set; }
        public decimal Sal_Cost { get; set; }
        public decimal Rtsl_Cost { get; set; }
        public decimal Trfrcp_Cost { get; set; }
        public decimal Trfdlv_Cost { get; set; }
        public decimal Lost_Cost { get; set; }
        public decimal Adj_Cost { get; set; }
        public decimal OpGroup_Cost { get; set; }
        public Nullable<decimal> Curbl_Qty { get; set; }
        public Nullable<decimal> Curbl_Cst { get; set; }
        public int ItemGroupNo { get; set; }
        public decimal StockIn { get; set; }
        public decimal StockInCost { get; set; }
        public decimal StockOut { get; set; }
        public decimal StockOutCost { get; set; }
        public decimal RetailPrices { get; set; }
        public decimal PurPrices { get; set; }
        public string Itm_Nmar { get; set; }
        public string Unit_NmAr { get; set; }
        public string Unit_Nm { get; set; }
    }
}
